export const inputLanguageObjectList = {
  NONE: "-",
  EN: "English",
  BG: "Bulgarian",
  ZH: "Chinese",
  CS: "Czech",
  DA: "Danish",
  DE: "German",
  EL: "Greek",
  ES: "Spanish",
  ET: "Estonian",
  FI: "Finnish",
  FR: "French",
  HU: "Hungarian",
  ID: "Indonesian",
  IT: "Italian",
  JA: "Japanese",
  KO: "Korean",
  LT: "Lithuanian",
  LV: "Latvian",
  NB: "Norwegian (Bokmål)",
  NL: "Dutch",
  PL: "Polish",
  PT: "Portuguese (Mixed Portuguese varieties)",
  RO: "Romanian",
  RU: "Russian",
  SK: "Slovak",
  SL: "Slovenian",
  SV: "Swedish",
  TR: "Turkish",
  UK: "Ukrainian",
};

export const outputLanguageObjectList = {
  // NONE: "-",
  EN: " English ",
  BG: " Bulgarian",
  ZH: " Chinese (simplified)",
  CS: " Czech",
  DA: " Danish",
  DE: " German",
  EL: " Greek",

  "EN-GB": "English (British)",
  "EN-US": "English (American)",
  ES: " Spanish",
  ET: " Estonian",
  FI: " Finnish",
  FR: " French",
  HU: " Hungarian",
  ID: " Indonesian",
  IT: " Italian",
  JA: " Japanese",
  KO: " Korean",
  LT: " Lithuanian",
  LV: " Latvian",
  NB: " Norwegian (Bokmål)",
  NL: " Dutch",
  PL: " Polish",
  PT: " Portuguese ",
  "PT-BR": " Portuguese (Brazilian)",
  "PT-PT": " Portuguese (Non-Brazilian Portuguese)",
  RO: " Romanian",
  RU: " Russian",
  SK: " Slovak",
  SL: " Slovenian",
  SV: " Swedish",
  TR: " Turkish",
  UK: " Ukrainian",
};
